name: "GitHub Actions runner OS system information"
description: "This action provides GitHub Actions runner OS information."
branding:
  icon: 'server'
  color: 'gray-dark'

outputs:
  cpu-core:
    description: "Logical CPU core size"
  cpu-model:
    description: "Logical CPU model name"
  hostname:
    description: "The host name of the operating system"
  kernel-release:
    description: "The kernel release"
  name:
    description: "The operating system (distribution) name"
  platform:
    description: "The operating system identity"
  release:
    description: "The operating system (distribution) release"
  totalmem:
    description: "the total amount of system memory in bytes"

runs:
  using: "node24"
  main: "lib/index.js"
